# Numpy Tutorials
NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python

### What is an array
An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type.

##### Points to remember:
- Arrays get referenced
- Vectorized operations: NumPy provides vectorized operations, which allow you to perform operations on entire arrays at once, rather than iterating over individual elements
- Matrix multiplication: Perform matrix multiplication using the @ operator

In [1]:
 ## initially lets import numpy
import numpy as np

In [2]:
my_lst = [1,2,3,4,5]
arr = np.array(my_lst)

In [3]:
 type(arr)

numpy.ndarray

In [4]:
 arr

array([1, 2, 3, 4, 5])

In [5]:
print(arr)

[1 2 3 4 5]


In [7]:
 arr.shape #gives out dimension of the array

(5,)

In [8]:
# Multinested array
my_lst1 = [1,2,3,4,5]
my_lst2 = [2,3,4,5,6]
my_lst3 = [9,7,6,8,9]

arr = np.array([my_lst1,my_lst2,my_lst3])

In [9]:
print(arr)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 7 6 8 9]]


In [10]:
arr.shape

(3, 5)

In [15]:
arrT = arr.reshape(5,3)
arrT

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [6, 8, 9]])

In [12]:
arr.shape

(3, 5)

In [19]:
## INDEXING
print( arr[:,:])

[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 7 6 8 9]]


In [20]:
print( arr[0:2,0:2])

[[1 2]
 [2 3]]


In [22]:
arr[1:,3:]

array([[5, 6],
       [8, 9]])

In [28]:
arr = np.arange(0,10,step = 2)
arr

array([0, 2, 4, 6, 8])

In [27]:
np.linspace(0,10,50) # gives equally spaced 50 numbers between 0 and 10 included

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [30]:
arr[3:] = 100
arr

array([  0,   2,   4, 100, 100])

In [32]:
arr1 = arr
print(arr1)

[  0   2   4 100 100]


In [34]:
arr1[3:] = 500
print(arr1)

[  0   2   4 500 500]


In [41]:
arr
# You will witness that the content of arr has changed as we made changes in arr1. This means that arr1 = arr this makes arr1 and arr share the same space and not a copy


array([  0,   2,   4, 500, 500])

In [45]:
# To make a true copy
arr2 = arr1.copy()
arr2[4:] = 1000
print(arr1)
print(arr2)

[  0   2   4 500 500]
[   0    2    4  500 1000]


In [48]:
# Some conditions useful in exploratory data analysis

val = 2
arr<val # gives true or false in the array where the condition satisfies

array([ True, False, False, False, False])

In [51]:
arr[arr<=val] # gives actual elements that satisfy the condition

array([0, 2])

In [56]:
arr/2 # operates in each individual array element

array([  0.,   1.,   2., 250., 250.])

In [59]:
# Create arrays and reshape
arr1 = np.arange(0,10).reshape(5,2)
arr1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [60]:
arr2 = arr1.copy()
arr1*arr2

array([[ 0,  1],
       [ 4,  9],
       [16, 25],
       [36, 49],
       [64, 81]])

In [61]:
np.ones(4)

array([1., 1., 1., 1.])

In [62]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [63]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [65]:
## random distribution
np.random.rand(3,3) # only between 0 and 1

array([[0.19562411, 0.23322118, 0.42126744],
       [0.84785437, 0.12034298, 0.11298148],
       [0.99012825, 0.83867326, 0.14047326]])

In [67]:
np.random.randn(4,4) # gives standard normal distribution 

array([[ 1.09218811,  0.30431308, -0.10743852, -0.74894951],
       [ 0.83268248, -1.53673425,  0.55044025, -1.06047292],
       [ 0.64005935,  1.84286338,  0.26176731,  0.57170976],
       [-0.15328321,  0.64234808, -0.34080495, -0.04169317]])

In [69]:
np.random.randint(0,100,8).reshape(4,2) # selects 8 integers between 0 and 1 in a 4x2 array

array([[34, 47],
       [95, 27],
       [ 0, 35],
       [63, 76]])